---
title: "isopod_app"
output: html_document
runtime: shiny
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(plotly)
library(cowplot) 
library(shiny)

```



```{r app, echo=F}

iso<-read.delim("Sample_001a.txt", header=T, sep="\t") # n


ui<-pageWithSidebar(
  
  headerPanel("Sample 001"),
  
  sidebarPanel(

    
    # checkboxes with input
    checkboxGroupInput("fam", # this will be our hook (input$fam on the server side)
                       c("Choose families:"),
                       choiceNames = # we can rename the input
                         list("Family 1", "Family 2",
                              "Family 3", "Family 4"),
                       choiceValues = # on the server side, input$var will be substituted with whatever we select
                         list("fam1", "fam2", "fam3", "fam4"), 
                              selected = "fam1"
    )
    
    
    ),

  mainPanel(plotOutput('plot1') # sent over from server
            )
)

server <- function(input, output) { # wrapper for server logic
  
  # look up reactive environment, this is where the magic happens:
  # https://shiny.rstudio.com/articles/reactivity-overview.html
  # Combine the selected variables into a new data frame
  plot1.dat <- reactive({ # this will return a 'reactive object', NOT a dataframe (see below)
    fams=input$fam # this returns a character vector from the checkboxes
    subs<-subset(iso, Family %in% fams) # this subsets our data frame

  })
  
  # render plot - "plot1" will be sent over to ui.R
    output$plot1 <- renderPlot({
      p<-ggplot(plot1.dat(), # the ()brackets here are important, they turn plot1.dat into a data frame
                aes(x=Length, y=Pigmentation, colour=Family)) +
    geom_point(size=4)
    p

  })
}


shinyApp(ui = ui, server = server)


```
